name: Setup SOPS
description: A GitHub Action for installing the SOPS CLI
author: Flux project
branding:
  color: blue
  icon: command
inputs:
  version:
    description: Strict SemVer of the SOPS CLI to install. Defaults to the latest release.
    required: false
runs:
  using: composite
  steps:
    - name: Download the binary to the runner's cache dir
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        if [[ -z "$VERSION" ]] || [[ "$VERSION" == "latest" ]]; then
          VERSION=$(curl -fsSL -H "Authorization: token ${{github.token}}" https://api.github.com/repos/getsops/sops/releases/latest | grep tag_name | cut -d '"' -f 4)
        fi
        if [[ -z "$VERSION" ]]; then
          echo "Unable to determine SOPS version"
        exit 1
        fi
        if [[ ! $VERSION = v* ]]; then
          VERSION="v${VERSION}"
        fi
        
        OS=$(echo "${RUNNER_OS}" | tr '[:upper:]' '[:lower:]')
        if [[ "$OS" == "macos" ]]; then
          OS="darwin"
        fi
        
        ARCH=$(echo "${RUNNER_ARCH}" | tr '[:upper:]' '[:lower:]')
        if [[ "$ARCH" == "x64" ]]; then
          ARCH="amd64"
        fi
        
        SOPS_EXEC_FILE="sops"
        if [[ "$OS" == "windows" ]]; then
            SOPS_EXEC_FILE="${SOPS_EXEC_FILE}.exe"
        fi
        
        SOPS_TOOL_DIR="${RUNNER_TOOL_CACHE}/sops/${VERSION}/${OS}/${ARCH}"
        if [[ ! -x "$SOPS_TOOL_DIR/$SOPS_EXEC_FILE" ]]; then
          DL_DIR="$(mktemp -dt sops-XXXXXX)"
          trap 'rm -rf $DL_DIR' EXIT
        
          echo "Downloading sops ${VERSION} for ${OS}/${ARCH}"
          SOPS_TARGET_FILE="sops-${VERSION}.${OS}.${ARCH}"
          if [[ "$OS" == "windows" ]]; then
            SOPS_TARGET_FILE="sops-${VERSION}.${ARCH}.exe"
          fi

          SOPS_DOWNLOAD_URL="https://github.com/getsops/sops/releases/download/${VERSION}/"
          echo "Downloading sops from $SOPS_DOWNLOAD_URL/$SOPS_TARGET_FILE"
          curl -fsSL -o "$DL_DIR/$SOPS_TARGET_FILE" "$SOPS_DOWNLOAD_URL/$SOPS_TARGET_FILE"

          echo "Installing sops to ${SOPS_TOOL_DIR}"
          mkdir -p "$SOPS_TOOL_DIR"
          mv "$DL_DIR/$SOPS_TARGET_FILE" "$SOPS_TOOL_DIR/$SOPS_EXEC_FILE"
          chmod +x "$SOPS_TOOL_DIR/$SOPS_EXEC_FILE"
        fi

        echo "Adding sops to path"
        echo "$SOPS_TOOL_DIR" >> "$GITHUB_PATH"

    - name: Print installed sops version
      shell: bash
      run: |
        sops --version
