name: Preview Release

on:
  workflow_dispatch:

jobs:
  preview-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions[bot]"
      - run: make tools
      - run: ./bin/flux-tools pkg prep --yes
      - run: git add .
      - run: git commit -m "Release preview" || true
      - run: ./bin/flux-tools pkg release --preview
